### ISSUE TITLE
Your example not working

### ISSUE THREAD

**Issue by wahidanvary** [yellowQ-software/yellowQ-Flutter-Image-Painter#1]
In your example modes selection is working but painting on the image not working and nothing changed. what is missing?!

**Comment by lively-bigyan** [comment]
@wahidanvary,
Thank you for opening up the issue. Could you please try and elaborate your issue? It is hard to speculate exactly what isn't working without the context. Like which flutter version are you using and what issues are you facing? A little code might help.

**Comment by wahidanvary** [comment]
I exactly used the copied of example code but not working correctly, Modes selection are working but using any selected mode not working. Please test again the example and tell me is working completely for you?

There are my flutter doctor details:

   • Flutter version 1.24.0-8.0.pre.251 at D:\sdkflutter
    • Framework revision 836efaecf0 (4 weeks ago), 2020-11-13 21:51:04 -0800
    • Engine revision e06f106385
    • Dart version 2.12.0 (build 2.12.0-40.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at d:/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Visual Studio - develop for Windows (Visual Studio Enterprise 2019 16.7.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
    • Visual Studio Enterprise 2019 version 16.7.30330.147
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

**Comment by lively-bigyan** [comment]
@wahidanvary I can confirm that all the modes are working for me right now on latest stable. If you are using the same code as example, maybe you forgot to add assets in the assets folder? Maybe try changing asset with network url image and using Image.network constructor. Let me know how that works out for you.

**Comment by wahidanvary** [comment]
I tried with many images. First, I declare my image in pubspec.yml:
```
assets:
    - images/ebargelogo.png
```

Then, I changed this line of the example:
```
Expanded(
              child: ImagePainter.asset("images/ebargelogo.png",
                  key: _imageKey, controller: imageController, scalable: true),
            ),
```

Image properly loaded on app, suddenly without working this package on it.

**Comment by lively-bigyan** [comment]
It seems like there is issue with beta branch of flutter. As of now, package is written and tested on latest stable version of flutter. We will be working on a fix shortly but until then, if you need to implement the feature,  please switch to the stable branch of flutter.

**Comment by wahidanvary** [comment]
Thank you, sir. My flutter channel was on the `master` channel, when I changed that to `stable` the package worked perfectly.
