### ISSUE TITLE
"Erase All" has the same tooltip as "undo" 

### ISSUE THREAD

**Issue by nekomaruh** [yellowQ-software/yellowQ-Flutter-Image-Painter#18]
In "_paint_over_image.dart" consider updating this:

```
IconButton(
            tooltip: **textDelegate.undo**,
            icon: widget.clearAllIcon ??
                const Icon(CommunityMaterialIcons.eraser),
            onPressed: () => setState(_paintHistory.clear),
          ),
```

To this:

```
IconButton(
            tooltip: **textDelegate.clearAllProgress**,
            icon: widget.clearAllIcon ??
                const Icon(CommunityMaterialIcons.eraser),
            onPressed: () => setState(_paintHistory.clear),
          ),
```

I forked this project and i love it, thumbs up to the creator!!

**Comment by lively-bigyan** [comment]
Hello, @nekomaruh (love the name BTW). Thank you for opening up the issue and bringing it over to my attention. I shall fix it soon. Feel free to open up PRs and contribute to the package if you develop something interesting on top of it.

**Comment by nekomaruh** [comment]
This issue was solved -> https://github.com/yellowQ-software/yellowQ-Flutter-Image-Painter/commit/3481577f83c71c8ccfd75948eae5f4d8c1242fca
