### ISSUE TITLE
Undo is not working when zooming in/out

### ISSUE THREAD

**Issue by nekomaruh** [yellowQ-software/yellowQ-Flutter-Image-Painter#19]
Can't undo changes when drawing, and after interacting with "view/zoom" option from menu. 
This could be a state problem, i can't find how to solve it.

**Comment by lively-bigyan** [comment]
Hi @nekomaruh, could you please attach the output of `flutter doctor`? We will look into the issue soon.

**Comment by nekomaruh** [comment]
This issue was solved -> https://github.com/yellowQ-software/yellowQ-Flutter-Image-Painter/commit/76cc17d6e65fd25ad0b300a28822f0aa9feb3f10

**Comment by guchengxi1994** [comment]
![bug](https://github.com/yellowQ-software/yellowQ-Flutter-Image-Painter/assets/33513462/1d2d66eb-183b-4c6c-9792-3ca6cb572621)

still has the same issue
