### ISSUE TITLE
Add fill color for closed objects in image

### ISSUE THREAD

**Issue by wahidanvary** [yellowQ-software/yellowQ-Flutter-Image-Painter#2]
It would be great if the fill color(like the flood fill algorithm) was added to modes.

**Comment by lively-bigyan** [comment]
Thank you for the issue. It was originally intended to be that way but it had some inconsistency across some of the modes, so it was removed during publication. But this I believe will be added in future versions of the package.

**Comment by lively-bigyan** [comment]
It is available in v0.1.5 but it will only work for closed shapes like in this case, circle and rectangle.

**Comment by wahidanvary** [comment]
It was great, really thank you. I would love to cooperate on this project. Is it possible? How can I cooperate?

**Comment by lively-bigyan** [comment]
> It was great, really thank you. I would love to cooperate on this project. Is it possible? How can I cooperate?

Yes for sure. Any collaborations are welcome. Here's how you can contribute:

1. Fork the project.
2. Branch out to new branch and modify.
3. Create a PR to merge your codebase to dev branch. 

Once we test the code, we will then merge it to master and publish them.

**Comment by wahidanvary** [comment]
> > It was great, really thank you. I would love to cooperate on this project. Is it possible? How can I cooperate?
> 
> Yes for sure. Any collaborations are welcome. Here's how you can contribute:
> 
> 1. Fork the project.
> 2. Branch out to new branch and modify.
> 3. Create a PR to merge your codebase to dev branch.
> 
> Once we test the code, we will then merge it to master and publish them.

Sure, Please tell me what is the future purpose and which modes do you want to upgrade?

**Comment by lively-bigyan** [comment]
Right now our priority would be to make the library work on the other versions other than stable of flutter. We are going to be using project workflow of image painter so any ongoing works should be listed there. If you find any interesting mode implementation, you can work on it and create a PR :)
