### ISSUE TITLE
How can I use "initialPaintMode" in version 0.31

### ISSUE THREAD

**Issue by sakura-sakai** [yellowQ-software/yellowQ-Flutter-Image-Painter#20]
For some reason my project uses flutter v1.22.6, so I can't use image_painter v0.4.0

**Comment by lively-bigyan** [comment]
I am sorry, I can't go ahead and add features to previous versions because every time I add something to the existing code, I'll have to publish the change. I would suggest you migrate the project. Or you can fork the project and modify it to work on 1.22.6.

**Comment by mickey-ichi** [comment]
I understand.
Thank you.

**Comment by sakura-sakai** [comment]
I understand.
Thank you.
