### ISSUE TITLE
create objects programmatically

### ISSUE THREAD

**Issue by Goddard** [yellowQ-software/yellowQ-Flutter-Image-Painter#24]
How would you recommend programmatically adding our own things to the image?

For example I want to have a special square with text inside of it drawn on specific x,y coordinates.

**Comment by lively-bigyan** [comment]
Right now that isn't something that is possible through the package. It is a simple implementation of allowing users to write and draw over images. But we are heading there next. We will definitely be working on it but it won't be anytime soon unless someone steps up to contribute. Thank you.
