### ISSUE TITLE
Text ModeData label set to Arrow

### ISSUE THREAD

**Issue by rtrevivian** [yellowQ-software/yellowQ-Flutter-Image-Painter#27]
_mode_widget.dart -> paintModes() -> Line 70
ModeData(
          icon: Icons.text_format,
          mode: PaintMode.text,
          label: textDelegate.arrow),

PaintMode.text ModeData label currently set to textDelegate.arrow should be changed textDelegate.text

**Comment by lively-bigyan** [comment]
Thanks for bringing this to my attention. This will be fixed on the next update if not fixed already.
