### ISSUE TITLE
No longer working on web?

### ISSUE THREAD

**Issue by kermitdefroghere** [yellowQ-software/yellowQ-Flutter-Image-Painter#30]
I know image_painter doesn't claim to work on web but it worked great for me months ago.
Now, exporting the image does not retain the background image. Only the most recently added foreground objects. 

Reverting back to Flutter 2.5 doesn't fix the problem.

Anyone having success using image_painter for web on Flutter 3+?

Might image_painter 1.0 support web?

**Comment by samaralii** [comment]
I'm facing the same issue

**Comment by sachinbpatil619** [comment]
yes facing the same issue

**Comment by towcar** [comment]
Web works for me. It wasn't initially, so I opened the project/library to try and solve this, and loaded up the example on Web. That worked right away.

I returned to my project and compared the differences in the example. Once I set the height and width my image displayed.

Here is my functioning code 
```
ImagePainter.memory(
      _imageModified,
      key: _painterKey,
      width: 700,
      height: 500,
      controlsAtTop: true,
    )
```
