### ISSUE TITLE
Hi, is there a way to change the zoom behaviour? 

### ISSUE THREAD

**Issue by SmearyQuill** [yellowQ-software/yellowQ-Flutter-Image-Painter#39]
When a horizontal image is loaded to the painter the image is really tinny, and when zoomed it doesn't changes it size, the zoom remains inside the area of the image.

Is there a way to change this behavior so the image scales using all the available space, maybe adding a new paint mode to allow crop? 

thank you.

**Comment by SmearyQuill** [comment]
In more details, when i load a horizontal image looks like this, but i want to be able to zoom in and out using the whole dark area, i partially managed to do this by removing a RectClip that was above the ImagePainterTransformer but the gesture area it's still constrained to the area that the original image was using and that messes up the gestures overall
![photo1659119953](https://user-images.githubusercontent.com/35876982/181823968-212740bc-3d65-4bcd-933b-99dbdbc77ce6.jpeg)
Here you can see a tiny difference, it's the same image just zoomed in, the image becomes larger, i'll try to make this work in the mean time
![photo1659119953 (1)](https://user-images.githubusercontent.com/35876982/181823976-09857b2d-26d0-4051-8c58-218eda246497.jpeg)

**Comment by lively-bigyan** [comment]
That's part of the reason why the package uses a confined space. When we give InteractiveViewer an unbounded space to work, it messes up the coordinate calculation. Also, there isn't enough demand for the feature to spend time on it.
