### ISSUE TITLE
PaintMode.Text Example

### ISSUE THREAD

**Issue by emircivas** [yellowQ-software/yellowQ-Flutter-Image-Painter#4]
Hi, Your Example File Does Not Contain Anything About Drawing Text On Image By Using ImagePainter.

**Comment by lively-bigyan** [comment]
Thank you for opening up the issue. There are some concerns to address right whether to add the text externally or internally. You can expect the implementation to be done within few days. Monday most probably.

**Comment by emircivas** [comment]
> Thank you for opening up the issue. There are some concerns to address right whether to add the text externally or internally. You can expect the implementation to be done within few days. Monday most probably.

Thank you for the quick reply (^^)
