### ISSUE TITLE
Why this package in not available for flutter web?

### ISSUE THREAD

**Issue by Hassan763** [yellowQ-software/yellowQ-Flutter-Image-Painter#48]
Want to know which hurdles you are facing on web version. I need simillar kind of work for web

**Comment by jobweegink** [comment]
We havent had the need ourselves to add this to web, you can always check and make a PR

**Comment by lively-bigyan** [comment]
It should work on the web as well. The recent version is built and debugged on the web. i/o will be different for the web though.
