### ISSUE TITLE
Text Icon color is not set 

### ISSUE THREAD

**Issue by noza0727** [yellowQ-software/yellowQ-Flutter-Image-Painter#49]
All the icons have a color of `Colors.grey[700]` except the Text icon. Because of that, when we change to dark mode, the color of the Text icon is changing to a lighter version which is not visible for the user. Is it possible to add color to the text icon also as it is done for others? And it would be even better, as an improvement, if the package could accept colors for icons. Thank you.

**Comment by esleptsovaINO** [comment]
I had the same problem. For now solved it with Theme:
`Theme(
          data: Theme.of(context)
              .copyWith(iconTheme: IconThemeData(color: Colors.grey[700])),
          child: ImagePainter.file(...),
        )`

**Comment by lively-bigyan** [comment]
Sorry for the late response. I haven't had the chance to actively work on the package lately. You can expect it to be done soon.

**Comment by lively-bigyan** [comment]
Resolved in v0.6.0.
