### ISSUE TITLE
  final Uint8List? image = await (imageKey.currentState!.exportImage()); taking 15 seconds

### ISSUE THREAD

**Issue by Jakoo13** [yellowQ-software/yellowQ-Flutter-Image-Painter#66]
Is this normal behavior for this function to take so long after painting on an image? Please help! 😅

**Comment by lively-bigyan** [comment]
It depends on the resolution of the image. High-quality images will take more time to export compared to low-quality ones. I suggest you utilize a compression library before editing the photo.

**Comment by Jakoo13** [comment]
> It depends on the resolution of the image. High-quality images will take more time to export compared to low-quality ones. I suggest you utilize a compression library before editing the photo.

Yes thank you I was able to fix this by lowering quality.
