### ISSUE TITLE
Widget keep loading...

### ISSUE THREAD

**Issue by luke1128qq** [yellowQ-software/yellowQ-Flutter-Image-Painter#69]
I import "image_painter: ^0.6.1" to my FlutterFlow project , but when I run it in "Test Mode" , it only shows the loading circle screen, and there are no error messages displayed

![img](https://github.com/yellowQ-software/yellowQ-Flutter-Image-Painter/assets/130536644/e9452304-c4cd-47cb-a2bd-480cb923c5c7)

![01](https://github.com/yellowQ-software/yellowQ-Flutter-Image-Painter/assets/130536644/8c031964-9b77-46d7-8175-59def4f5c250)

![02](https://github.com/yellowQ-software/yellowQ-Flutter-Image-Painter/assets/130536644/1ea6e51e-1764-4411-8980-23b0fbc3fb18)

**Comment by lively-bigyan** [comment]
It seems like you are using Flutterflow platform. Since this library is written and tested on the Flutter development environment, we cannot debug the issues on 3rd party frameworks. Please give it a try with flutter development environment and see if you run into same or similar issue.

**Comment by lcundiff** [comment]
@luke1128qq Did you find a fix for this? Is because the image parameter is looking for the sample image?

**Comment by luke1128qq** [comment]
> Did you find a fix for this? Is because the image parameter is looking for the sample image?

I couldn't resolve this bug in FlutterFlow, so eventually, I gave up on incorporating this package.
